version: '3.3'

services:
  db:
    image: mysql/mysql-server:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    ports:
      - "8001:80"
    restart: always
    volumes:
      - ./plugins/quant:/var/www/html/wp-content/plugins/quant
      - ./uploads:/var/www/html/wp-content/uploads
      - ./config/wp-config.php:/var/www/html/wp-config.php
    networks:
      - quant-network
      - default

volumes:
  db_data: {}

networks:
  quant-network:
    external: true
